Style table
Pixilib/GaelO_Flow_Frontend pull request #116
Opened 2024-02-20 14:24 UTC by SophieLab

#114 #112 
Modifications :

    **Generality of the Table component:**
       - Fixed errors.
       - Added additional props.
        - Added Overflow.

    **Styling of the badge for port cells:**
     - Updated the badge style in the specific RedisCard and OrthancCard components for better visibilit

2024-02-20 14:50 UTC, salimkanoun requested changes

2024-02-20 14:50 UTC, salimkanoun commented on src/Header.tsx
> +    useOutsideClick(settingsDropdownRef, () => isOpen('SettingsUser') && handleDropDown('SettingsUser'));
@remixxx31 ne pas centraliser les listener

2024-02-20 14:50 UTC, salimkanoun commented on src/RenderComponents/Menu/MenuItemsCollapse.tsx
> +      {isOpen && <SideBarItems myRef={myRef} elements={elements} onNavigate={onNavigate} />}
@remixxx31 les Ref c'est pas terrible à quoi ca sert ici ? surtout ici en plus tu fais passer une ref en props.

Globalement les Refs c'est plutot bad code, c'est pas interdit d'utiliser mais c'est pas terrible c'est pas l'esprit de react

2024-02-20 14:50 UTC, salimkanoun commented on src/admin/general/OrthancCard.tsx
> +            setData(loadedData);
@SophieLab tu peux implementer l'API maintenant, faut faire docker compose pull  puis docker compose up pour récupérer la derniere version du code d'antonin et tu devrai avoir les info orthanc dans l'API d'option

2024-02-20 14:50 UTC, salimkanoun commented on src/admin/general/OrthancCard.tsx
> +                    <Button color={Colors.primary} onClick={() => console.log('Info action')}><Info /></Button>
Appel d'API à implementer, @SophieLab voit avec @remixxx31 pour faire ca demain, les API sont dispo normalement

2024-02-20 14:50 UTC, salimkanoun commented on src/admin/general/RedisCard.tsx
> +                setData(loadedData);
Appel d'API a implementer

2024-02-20 14:50 UTC, salimkanoun commented on src/admin/general/RedisCard.tsx
> +                setData(loadedData);
avec tanstack query

2024-02-21 12:38 UTC, remixxx31 commented on src/RenderComponents/Menu/MenuItemsCollapse.tsx
> +      {isOpen && <SideBarItems myRef={myRef} elements={elements} onNavigate={onNavigate} />}
Les refs ça me sert à détecter les clics en dehors des menus déroulants.
Quand je clique à l'extérieur de ma liste, la liste se referme.

C'est ce que j'ai trouvé de mieux pour réaliser ça, est-ce qu'il y a une meilleure solution ?
Le fait de passer en props c'était pour éviter de mettre de la logique dans des composants qui sont plutôt des composants de rendu. 

Je mets plutôt directement la ref dans le composant qui en a besoin du coup @salimkanoun  ?
En fait actuellement j'ai toute la logique dans Header et Banner, BannerItems, ToogleChevronsont des components de rendu.

2024-02-21 12:44 UTC, remixxx31 commented on src/RenderComponents/Menu/MenuItemsCollapse.tsx
> +      {isOpen && <SideBarItems myRef={myRef} elements={elements} onNavigate={onNavigate} />}
Pardon je découvre des issues qui sont en lien avec tes remarques

2024-02-21 13:30 UTC, salimkanoun commented on src/RenderComponents/Menu/MenuItemsCollapse.tsx
> +      {isOpen && <SideBarItems myRef={myRef} elements={elements} onNavigate={onNavigate} />}
Hmmm pour detecter une sortir de composant tu peux tenter onBlur,
Par ailleurs tu n'est pas obligé d'amener ton clic jusqu'à ton composant de render pour ca, tu peux wrapper ton composant de render dans une simple div dans le composant parent qui lui ecoute l'evenement onBlur

2024-02-26 21:35 UTC, closed without merging