New aet
Pixilib/GaelO_Flow_Frontend pull request #158
Opened 2024-03-21 14:46 UTC by SophieLab

**NewAet Component :** 

- A NewAet component has been created and is now linked to the "New Aet" button in the AetCard component. This allows the component to deploy when the user clicks on the button.

**Overall Visual Improvements:**

- The application's background has been stylized to offer a better user experience.
- The ability to customize the colors of CardHeader, CardBody, and CardFooter components has been added through a new color prop.

- The style of the text in the Filter component has been modified to make it smaller and less bold.

**Encountered Issues:**

-  I tried to adjust the size of the banner so that it extends behind the sidebar and occupies the entire available length of the screen. However, this modification requires further review as the banner does not yet take up the full length of the screen as expected...

- I am encountering a problem with setting the GrayCustom color for Cardbody in NewAet. Despite several attempts, the color does not apply as expected. Any help or suggestion to solve this problem would be greatly appreciated.

2024-03-21 14:54 UTC, remixxx31 requested changes
just change mb-*

2024-03-21 14:54 UTC, remixxx31 commented on src/admin/general/OrthancCard.tsx
Tu as oublié quelque chose à droite de mb si tu veux appliquer un marging bottom

2024-03-21 15:09 UTC, remixxx31 requested changes
C'est bien , juste deux petit trucs à changer de ce que je vois!

2024-03-21 15:09 UTC, remixxx31 commented on src/root/RootApp.tsx
Priviliéger les classes css , ;)

2024-03-21 15:09 UTC, remixxx31 commented on src/ui/Card.tsx
> +const CardFooter = ({ children, className = "", color }: FooterProps) => {
Je pense que className=" " ne sert à rien, tu peux te contenter de className, je pense.

2024-03-25 11:19 UTC, SophieLab commented on src/ui/Card.tsx
> +const CardFooter = ({ children, className = "", color }: FooterProps) => {
mh.. je crois que que c'est pour éviter les erreurs  et permettre d'avoir  au moins une chaîne vide, c'est juste pour être sûr qu'il y ait quelque chose à utiliser même si on ne met pas un nom de classe. Si il  ya une absence de valeur il peut y avoir des bugs je pense ( à vérifier) ^^ parce que du coup j'ai un doute maitnenant.

2024-03-26 09:29 UTC, merged